//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrjMaillotsSoccer
{
    public partial class Default
    {
        /// <summary>
        /// Contrôle chkCanada.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkCanada;

        /// <summary>
        /// Contrôle chkUSA.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkUSA;

        /// <summary>
        /// Contrôle chkMexique.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkMexique;

        /// <summary>
        /// Contrôle btnReset.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnReset;

        /// <summary>
        /// Contrôle ddlSort.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlSort;

        /// <summary>
        /// Contrôle rptMaillots.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptMaillots;

        /// <summary>
        /// Contrôle rptPagination.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptPagination;

        /// <summary>
        /// Contrôle btnPrev.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnPrev;

        /// <summary>
        /// Contrôle btnNext.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnNext;
    }
}
